apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer-security
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    {{- include "wazuh.indexer.selectorLabels" . | nindent 4 }}
data:
  internal_users.yml: |
    ---
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: {{ .Values.security.indexerPasswordHash | quote }}
      reserved: true
      backend_roles:
      - "admin"
      description: "Admin user"
    kibanaserver:
      hash: {{ .Values.security.kibanaserverPasswordHash | quote }}
      reserved: true
      description: "Dashboard server user"
