{{- if not .Values.security.existingSecrets.indexer }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer-credentials
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    {{- include "wazuh.indexer.selectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.security.indexerUsername | quote }}
  password: {{ .Values.security.indexerPassword | quote }}
{{- end }}
