apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wazuh.fullname" . }}-manager-config
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    {{- include "wazuh.manager.selectorLabels" . | nindent 4 }}
data:
  ossec.conf: |
    <ossec_config>
      <global>
        <jsonout_output>yes</jsonout_output>
        <alerts_log>yes</alerts_log>
        <logall>no</logall>
        <logall_json>{{ ternary "yes" "no" .Values.manager.logallJson }}</logall_json>
        <email_notification>no</email_notification>
      </global>

      <remote>
        <connection>secure</connection>
        <port>1514</port>
        <protocol>tcp</protocol>
        <queue_size>131072</queue_size>
      </remote>

      <auth>
        <disabled>no</disabled>
        <port>1515</port>
        <use_source_ip>no</use_source_ip>
        <purge>yes</purge>
        <use_password>no</use_password>
        <ssl_agent_ca></ssl_agent_ca>
        <force>
          <enabled>yes</enabled>
          <disconnected_time enabled="yes">1h</disconnected_time>
          <after_registration_time>1h</after_registration_time>
          <key_mismatch>yes</key_mismatch>
        </force>
      </auth>

      <alerts>
        <log_alert_level>3</log_alert_level>
        <email_alert_level>12</email_alert_level>
      </alerts>

      <vulnerability-detection>
        <enabled>yes</enabled>
        <index-status>yes</index-status>
        <feed-update-interval>{{ .Values.manager.feedUpdateInterval }}</feed-update-interval>
      </vulnerability-detection>

      <indexer>
        <enabled>yes</enabled>
        <hosts>
          <host>https://{{ include "wazuh.fullname" . }}-indexer:9200</host>
        </hosts>
        <ssl>
          <certificate_authorities>
            <ca>/etc/ssl/root-ca.pem</ca>
          </certificate_authorities>
          <certificate>/etc/ssl/filebeat.pem</certificate>
          <key>/etc/ssl/filebeat-key.pem</key>
        </ssl>
      </indexer>

      <ruleset>
        <decoder_dir>ruleset/decoders</decoder_dir>
        <rule_dir>ruleset/rules</rule_dir>
        <rule_exclude>0215-policy_rules.xml</rule_exclude>
        <list>etc/lists/audit-keys</list>
        <list>etc/lists/amazon/aws-eventnames</list>
        <list>etc/lists/security-eventchannel</list>
      </ruleset>
    </ossec_config>
  filebeat.yml: |
    filebeat.modules:
      - module: wazuh
        alerts:
          enabled: true
        archives:
          enabled: {{ .Values.manager.logallJson }}

    setup.template.json.enabled: true
    setup.template.overwrite: true
    setup.template.json.path: '/etc/filebeat/wazuh-template.json'
    setup.template.json.name: 'wazuh'
    setup.ilm.enabled: false
    output.elasticsearch:
      hosts: [https://{{ include "wazuh.fullname" . }}-indexer:9200]
      username: '{{ .Values.security.indexerUsername }}'
      password: '{{ .Values.security.indexerPassword }}'
      ssl.verification_mode: 'certificate'
      ssl.certificate_authorities: ['/etc/ssl/root-ca.pem']
      ssl.certificate: '/etc/ssl/filebeat.pem'
      ssl.key: '/etc/ssl/filebeat-key.pem'

    logging.metrics.enabled: false

    seccomp:
      default_action: allow
      syscalls:
      - action: allow
        names:
        - rseq
