apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-credentials
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
type: Opaque
stringData:
  indexer-username: {{ .Values.security.indexerUsername | quote }}
  indexer-password: {{ .Values.security.indexerPassword | quote }}
  api-username: {{ .Values.security.apiUsername | quote }}
  api-password: {{ .Values.security.apiPassword | quote }}
